const CONFIG = [
    { word: 'Gravitrax', image: require('../assets/Gravitrax.png') },
    { word: 'Apfel', image: require('../assets/apple.png') },
    { word: 'Banane', image: require('../assets/banana.png') },
    { word: 'Trauben', image: require('../assets/grapes.png') },
    { word: 'Kiwi', image: require('../assets/kiwi.png'), syllables: ['Ki', 'wi'] },
    { word: 'Wassermelone', image: require('../assets/watermelon.png'), syllables: ['Wa', 'sser', 'me', 'lo', 'ne'] },
    { word: 'Baum', image: require('../assets/tree.png') },
    { word: 'Torte', image: require('../assets/cake.png') },
    { word: 'Haus', image: require('../assets/house.png') },
    { word: 'Katze', image: require('../assets/cat.png') },
    { word: 'Hund', image: require('../assets/dog.png') },
    { word: 'Sonic', image: require('../assets/sonic.png') },
    { word: 'Mario', image: require('../assets/mario.png') },
    { word: 'Sonne', image: require('../assets/sun.png') },
    { word: 'Wasser', image: require('../assets/water.png') },
    { word: 'Ball', image: require('../assets/ball.png') },
    { word: 'Schlüssel', image: require('../assets/key.png') },
    { word: 'Pikachu', image: require('../assets/pikachu.png'), syllables: ['Pi', 'ka', 'chu'] },
    { word: 'Auto', image: require('../assets/car.png') },
    { word: 'Löwe', image: require('../assets/lion.png'), syllables: ['Lö', 'we'] },
    { word: 'Buch', image: require('../assets/book.png') },
    { word: 'Tasse', image: require('../assets/cup.png') },
    { word: 'Gabel', image: require('../assets/fork.png'), syllables: ['Ga', 'bel'] },
    { word: 'Bett', image: require('../assets/Bett.png') },
    { word: 'Tür', image: require('../assets/door.png') },
    { word: 'Tisch', image: require('../assets/table.png') },
    { word: 'Pedale', image: require('../assets/Pedale.png'), syllables: ['Pe', 'da', 'le'] },
    { word: 'Affe', image: require('../assets/monkey.png') },
    { word: 'Brot', image: require('../assets/bread.png') },
    { word: 'Teller', image: require('../assets/plate.png') },
    { word: 'Wurst', image: require('../assets/sausage.png') },
    { word: 'Pizza', image: require('../assets/pizza.png'), syllables: ['Pi', 'zza'] },
    { word: 'Videospiel', image: require('../assets/videogame.png'), syllables: ['Vi', 'de', 'o', 'spiel'] },
    { word: 'Herz', image: require('../assets/heart.png') },
    { word: 'Bär', image: require('../assets/bear.png') },
    { word: 'Wal', image: require('../assets/whale.png') },
    { word: 'Nase', image: require('../assets/nose.png'), syllables: ['Na', 'se'] },
    { word: 'Ski', image: require('../assets/ski.png') },
    { word: 'Pokal', image: require('../assets/trophy.png') },
    { word: 'Tiger', image: require('../assets/tiger.png') },
    { word: 'Berge', image: require('../assets/mountains.png') },
    { word: 'Brille', image: require('../assets/glasses.png'), syllables: ['Bri', 'lle'] },
    { word: 'Hut', image: require('../assets/hat.png') },
    { word: 'Uhr', image: require('../assets/clock.png') },
    { word: 'Gurke', image: require('../assets/cucumber.png'), syllables: ['Gur', 'ke'] },
    { word: 'Velo', image: require('../assets/bicycle.png') },
    { word: 'Fisch', image: require('../assets/fish.png') },
    { word: 'Hai', image: require('../assets/shark.png') },
    { word: 'Bus', image: require('../assets/bus.png') },
    { word: 'Mond', image: require('../assets/moon.png') },
    { word: 'Kran', image: require('../assets/crane.png') },
    { word: 'Tomate', image: require('../assets/tomato.png'), syllables: ['To', 'ma', 'te'] },
    { word: 'Polizei', image: require('../assets/cop.png') },
    { word: 'Titanic', image: require('../assets/titanic.png'), syllables: ['Ti', 'ta', 'nic'] },
    { word: 'Lego', image: require('../assets/lego.png') },
    { word: 'Ronaldo', image: require('../assets/ronaldo.png'), syllables: ['Ro', 'nal', 'do'] },
    { word: 'Messi', image: require('../assets/messi.png') },
    { word: 'Zug', image: require('../assets/train.png') },
    { word: 'Rakete', image: require('../assets/rocket.png'), syllables: ['Ra', 'ke', 'te'] },
    { word: 'Maus', image: require('../assets/mouse.png') },
    { word: 'Globi', image: require('../assets/Globi.png') },
    { word: 'Ballon', image: require('../assets/balloon.png') },
    { word: 'Federer', image: require('../assets/federer.png'), syllables: ['Fe', 'de', 'rer'] },
    { word: 'Käse', image: require('../assets/cheese.png') },
    { word: 'Boot', image: require('../assets/boat.png') },
    { word: 'Medalie', image: require('../assets/medal.png') },
    { word: 'Eis', image: require('../assets/icecream.png') },
    { word: 'Hose', image: require('../assets/pants.png') },
    { word: 'Pflanze', image: require('../assets/plant.png') },
    { word: 'Maske', image: require('../assets/mask.png') },
    { word: 'Messer', image: require('../assets/knife.png') },
    { word: 'Löffel', image: require('../assets/spoon.png') },
    { word: 'Augen', image: require('../assets/eyes.png'), syllables: ['Au', 'gen'] },
    { word: 'Rad', image: require('../assets/wheel.png') },
    { word: 'Sofa', image: require('../assets/sofa.png') },
    { word: 'Laptop', image: require('../assets/laptop.png') },
    { word: 'Radio', image: require('../assets/radio.png') },
    { word: 'Garten', image: require('../assets/garten.png') },
    { word: 'Stern', image: require('../assets/Stern.png') },
    { word: 'Stuhl', image: require('../assets/stuhl.png') },
    { word: 'Vogel', image: require('../assets/vogel.png') },
    { word: 'Blume', image: require('../assets/blume.png') },
    { word: 'Fabrik', image: require('../assets/Fabrik.png') },
    { word: 'Bagger', image: require('../assets/Bagger.png') },
    { word: 'Roboter', image: require('../assets/Roboter.png') },
    { word: 'Dino', image: require('../assets/Dino.png') },
    { word: 'Fuss', image: require('../assets/Fuss.png') },
    { word: 'Igel', image: require('../assets/Igel.png') },
    { word: 'Kissen', image: require('../assets/Kissen.png') },
    { word: 'Blatt', image: require('../assets/Blatt.png') },
    { word: 'Pferd', image: require('../assets/Pferd.png') },
    { word: 'Kuh', image: require('../assets/Kuh.png') },
    { word: 'Socken', image: require('../assets/Socken.png') },
    { word: 'Vase', image: require('../assets/Vase.png') },
    { word: 'Hand', image: require('../assets/Hand.png') },
    { word: 'Koch', image: require('../assets/Koch.png') },
    { word: 'Birne', image: require('../assets/Birne.png') },
    { word: 'Helm', image: require('../assets/Helm.png') },
    { word: 'Spinne', image: require('../assets/Spinne.png') },
    { word: 'Panda', image: require('../assets/Panda.png') },
    { word: 'Rampe', image: require('../assets/Rampe.png') },
    { word: 'Delfin', image: require('../assets/Delfin.png') },
    { word: 'Planet', image: require('../assets/Planet.png') },
    { word: 'Geld', image: require('../assets/Geld.png') },
    { word: 'Töff', image: require('../assets/Toeff.png') },
    { word: 'Pommes', image: require('../assets/Pommes.png') },
    { word: 'Karotte', image: require('../assets/Karotte.png'), syllables: ['Ka', 'ro', 'tte'] },
    { word: 'Ninjago', image: require('../assets/Ninjago.png'), syllables: ['Nin', 'ja', 'go'] },
    { word: 'Taxi', image: require('../assets/Taxi.png') },
    { word: 'Fussball', image: require('../assets/Fussball.png') },
    { word: 'Backflip', image: require('../assets/Backflip.png') },
    { word: 'Nuss', image: require('../assets/Nuss.png') },
    { word: 'Zoo', image: require('../assets/Zoo.png') },
    { word: 'Arzt', image: require('../assets/Arzt.png') },
    { word: 'Ärztin', image: require('../assets/Aerztin.png') },
    { word: 'Rennen', image: require('../assets/Rennen.png') },
    { word: 'Keller', image: require('../assets/Keller.png') },
    { word: 'Schwein', image: require('../assets/Schwein.png') },
    { word: 'Star Wars', image: require('../assets/Star_Wars.png') },
    { word: 'Krokodil', image: require('../assets/krokodil.png'), syllables: ['Kro', 'ko', 'dil'] },
    { word: 'Schnecke', image: require('../assets/Schnecke.png') },
    { word: 'Glurak', image: require('../assets/Glurak.png') },
    { word: 'Mew Two', image: require('../assets/Mew_Two.png') },
    { word: 'Mew', image: require('../assets/Mew.png') },
    { word: 'Turtok', image: require('../assets/Turtok.png') },
    { word: 'Harry Potter', image: require('../assets/Harry_Potter.png') },
    { word: 'Draco', image: require('../assets/Draco.png') },
    { word: 'Voldemort', image: require('../assets/Voldemort.png'), syllables: ['Vol', 'de', 'mort'] },
    { word: 'Justus', image: require('../assets/Justus.png') },
    { word: 'Peter', image: require('../assets/Peter.png') },
    { word: 'Bob', image: require('../assets/Bob.png') },
    { word: 'Minion', image: require('../assets/Minion.png'), syllables: ['Mi', 'ni', 'on'] },
    { word: 'Murmli', image: require('../assets/Murmli.png') },
    { word: 'Schatz', image: require('../assets/Schatz.png') },
    { word: 'Alien', image: require('../assets/Alien.png'), syllables: ['A', 'li', 'en'] },
    { word: 'Flugzeug', image: require('../assets/Flugzeug.png') },
    { word: 'Rose', image: require('../assets/Rose.png'), syllables: ['Ro', 'se'] },
    { word: 'Kartoffel', image: require('../assets/Kartoffel.png'), syllables: ['Kar', 'to', 'ffel'] },


  /******************** CHOOSE OPTION ****************************/


  {
    question: 'Wer ist der beste?',
    imageAnswers: {
      images: [require('../assets/messi.png'), require('../assets/haaland.png'), require('../assets/mbappe.png'), require('../assets/ronaldo.png')],
      correct: [0],
    },
  },
  {
    question: 'Wer fliegt?',
    imageAnswers: {
      images: [require('../assets/bear.png'), require('../assets/tiger.png'), require('../assets/vogel.png'), require('../assets/krokodil.png')],
      correct: [2],
    },
  },
  {
    question: 'Wer schwimmt besser?',
    imageAnswers: {
      images: [require('../assets/dog.png'), require('../assets/lion.png'), require('../assets/Igel.png'), require('../assets/shark.png')],
      correct: [3],
    },
  },
  {
    question: 'Wer spielt Tennis?',
    imageAnswers: {
      images: [require('../assets/ronaldo.png'), require('../assets/federer.png'), require('../assets/messi.png'), require('../assets/mbappe.png')],
      correct: [1],
    },
  },
  {
    question: 'Wer spielt Fussball?',
    imageAnswers: {
      images: [require('../assets/ronaldo.png'), require('../assets/federer.png'), require('../assets/messi.png'), require('../assets/mbappe.png')],
      correct: [0,2,3],
    },
  },
  {
    question: 'Wer ist der Koch?',
    imageAnswers: {
      images: [require('../assets/Arzt.png'), require('../assets/cop.png'), require('../assets/Koch.png'), require('../assets/Aerztin.png')],
      correct: [2],
    },
  },
  {
    question: 'Wer ist der Arzt?',
    imageAnswers: {
      images: [require('../assets/Arzt.png'), require('../assets/cop.png'), require('../assets/Koch.png'), require('../assets/Aerztin.png')],
      correct: [0],
    },
  },
  {
    question: 'Wer ist der Polizist?',
    imageAnswers: {
      images: [require('../assets/Arzt.png'), require('../assets/cop.png'), require('../assets/Koch.png'), require('../assets/Aerztin.png')],
      correct: [1],
    },
  },
  {
    question: 'Wer ist die Ärztin?',
    imageAnswers: {
      images: [require('../assets/Arzt.png'), require('../assets/cop.png'), require('../assets/Koch.png'), require('../assets/Aerztin.png')],
      correct: [3],
    },
  },
  {
    question: 'Wer ist schneller?',
    imageAnswers: {
      images: [require('../assets/Schnecke.png'), require('../assets/Toeff.png'), require('../assets/Panda.png'), require('../assets/Igel.png')],
      correct: [1],
    },
  },
  {
    question: 'Wer ist langsamer?',
    imageAnswers: {
      images: [require('../assets/Schnecke.png'), require('../assets/Toeff.png'), require('../assets/Panda.png'), require('../assets/Igel.png')],
      correct: [0],
    },
  },
  {
    question: 'Welches ist süss?',
    imageAnswers: {
      images: [require('../assets/Pommes.png'), require('../assets/cucumber.png'), require('../assets/bread.png'), require('../assets/apple.png')],
      correct: [3],
    },
  },
  {
    question: 'Welches ist die Sonne?',
    imageAnswers: {
      images: [require('../assets/sun.png'), require('../assets/Planet.png'), require('../assets/moon.png'), require('../assets/Stern.png')],
      correct: [0],
    },
  },
  {
    question: 'Welcher ist der Planet?',
    imageAnswers: {
      images: [require('../assets/sun.png'), require('../assets/Planet.png'), require('../assets/moon.png'), require('../assets/Stern.png')],
      correct: [1],
    },
  },
  {
    question: 'Welches ist der Mond?',
    imageAnswers: {
      images: [require('../assets/sun.png'), require('../assets/Planet.png'), require('../assets/moon.png'), require('../assets/Stern.png')],
      correct: [2],
    },
  },
  {
    question: 'Welcher ist der Stern?',
    imageAnswers: {
      images: [require('../assets/sun.png'), require('../assets/Planet.png'), require('../assets/moon.png'), require('../assets/Stern.png')],
      correct: [3],
    },
  },
  {
    question: 'Wer gibt Milch?',
    imageAnswers: {
      images: [require('../assets/cat.png'), require('../assets/Kuh.png'), require('../assets/monkey.png'), require('../assets/dog.png')],
      correct: [1],
    },
  },
  {
    question: 'Wer ist Pikachus Trainer?',
    imageAnswers: {
      images: [require('../assets/Serena.png'), require('../assets/Leaf.png'), require('../assets/Red.png'), require('../assets/Ash.png')],
      correct: [3],
    },
  },
  {
    question: 'Welches ist Globi?',
    imageAnswers: {
      images: [require('../assets/Globi.png'), require('../assets/pikachu.png'), require('../assets/mario.png'), require('../assets/sonic.png')],
      correct: [0],
    },
  },
  {
    question: 'Welches ist Pikachu?',
    imageAnswers: {
      images: [require('../assets/mario.png'), require('../assets/sonic.png'), require('../assets/pikachu.png'), require('../assets/Globi.png')],
      correct: [2],
    },
  },
  {
    question: 'Welcher ist Sonic?',
    imageAnswers: {
      images: [require('../assets/mario.png'), require('../assets/sonic.png'), require('../assets/Globi.png'), require('../assets/pikachu.png')],
      correct: [1],
    },
  },
  {
    question: 'Welches ist Mario?',
    imageAnswers: {
      images: [require('../assets/sonic.png'), require('../assets/Globi.png'), require('../assets/pikachu.png'), require('../assets/mario.png')],
      correct: [3],
    },
  },
  {
    question: 'Welcher ist Harry Potter?',
    imageAnswers: {
      images: [require('../assets/Draco.png'), require('../assets/Harry_Potter.png'), require('../assets/Voldemort.png')],
      correct: [1],
    },
  },
  {
    question: 'Welcher ist Draco?',
    imageAnswers: {
      images: [require('../assets/Draco.png'), require('../assets/Harry_Potter.png'), require('../assets/Voldemort.png')],
      correct: [0],
    },
  },
  {
    question: 'Welcher ist Voldemort?',
    imageAnswers: {
      images: [require('../assets/Voldemort.png'), require('../assets/Draco.png'), require('../assets/Harry_Potter.png')],
      correct: [0],
    },
  },
  {
    question: 'Welcher ist Räuber Hotzenplotz?',
    imageAnswers: {
      images: [require('../assets/Harry_Potter.png'), require('../assets/Hotzenplotz.png')],
      correct: [1],
    },
  },
  {
    question: 'Welcher ist Peter?',
    imageAnswers: {
      images: [require('../assets/Justus.png'), require('../assets/Peter.png'), require('../assets/Bob.png')],
      correct: [1],
    },
  },
  {
    question: 'Welcher ist Justus?',
    imageAnswers: {
      images: [require('../assets/Justus.png'), require('../assets/Bob.png'), require('../assets/Peter.png')],
      correct: [0],
    },
  },
  {
    question: 'Welcher ist Bob?',
    imageAnswers: {
      images: [require('../assets/Bob.png'), require('../assets/Peter.png'), require('../assets/Justus.png')],
      correct: [0],
    },
  },
  {
    question: 'Wer hat blonde Haare??',
    imageAnswers: {
      images: [require('../assets/Peter.png'), require('../assets/Bob.png'), require('../assets/Justus.png')],
      correct: [1],
    },
  },
];

export default CONFIG;
